### ISSUE TITLE
Atom ctags-linux without exec permission

### ISSUE THREAD

**Issue by Costallat** [y2kbadbug/gentoo-overlay#1]
I had to give /usr/share/atom/resources/app.asar.unpacked/node_modules/symbols-view/vendor/ctags-linux execution permission to make module 'symbol-view' work with c/c++.

Possible solution:
chmod +x /usr/share/atom/resources/app.asar.unpacked/node_modules/symbols-view/vendor/ctags-linux

Atom 1.0.2

Can you check this?

How to Reproduce:

Open one C++ file, and press the "ctrl + shift + r" to invoke symbols, it will give an error because ctags-linux, can't be called since it doesn't have an execution permission!

Tks.
Renato Foot Guimarães Costallat

**Comment by y2kbadbug** [comment]
I updated the ebuild to make that specific file executable, didn't see any harm in doing so.  Let me know if this works for you.

**Comment by Costallat** [comment]
Yes, it solved.

Sorry, I forget to say how to reproduce the error, I will edit the first message to add an example!
