### ISSUE TITLE
Failed checksum verification of NzbDrone.master.tar.gz

### ISSUE THREAD

**Issue by gclawes** [y2kbadbug/gentoo-overlay#2]
Checksum verification of NxbDrone.master.tar.gz fails because the file is downloaded from the Sonarr update URL (http://update.sonarr.tv/v2/master/mono/NzbDrone.master.tar.gz), which changes regularly.

```
2015-08-23 20:01:16 (175 KB/s) - _/usr/portage/distfiles/NzbDrone.master.tar.gz_ saved [6144167/6144167]

!!! Fetched file: NzbDrone.master.tar.gz VERIFY FAILED!
!!! Reason: Filesize does not match recorded size
!!! Got:      6144167
!!! Expected: 5883224
Refetching... File renamed to '/usr/portage/distfiles/NzbDrone.master.tar.gz._checksum_failure_.pIAL_h'
```

Using the version '9999' is usually reserved for building from source.  Packages from the update URL are pre-compiled.

**Comment by gclawes** [comment]
Running `ebuild sonarr-9999.ebuild manifest --force` in `/var/lib/layman/y2kbadbug/net-nntp/sonarr` fixes the issue as a short-term fix

**Comment by y2kbadbug** [comment]
I didn't think about that when I created the ebuild.  Unfortunately after I created my repo and after having several negative experiences with the Gentoo community I decided to switch to Arch.  I just got tired of how downhill the community became.  I am keeping this up for archival purposes, feel free to fork if you want.  Ill submit a bug to Gentoo to remove it from the list.

**Comment by gclawes** [comment]
A package like this should probably be build from source.  Unfortunately, I've got no experience building mono packages, so that's something I'd have to dive into before attempting this.

**Comment by y2kbadbug** [comment]
There are several issues with building it from source, the developers don't play fair.  Building from source takes a very long time, they do not use a proper version system so I had try and pull from the tags in GitHub.  It took several hours of work getting the ebuild to even compile it all, and when it did, it didn't even work.

Using their binary made one was just easier.  Also, I believe there is a useflag that will enable the auto updater, which means after you install it once you don't have to every again, NzbDrone will just do.  I bet if you just go into the port directory and do an ebuild digest on the file it will fix it.

Again, I apologize, I already got my overlay removed from the list.
