### ISSUE TITLE
Overlay still exist?

### ISSUE THREAD

**Issue by iandoug** [y2kbadbug/gentoo-overlay#7]
Hi
trooper ~ # layman -a y2kbadbug

 * Adding overlay...
 * Exception: Overlay "y2kbadbug" does not exist.

 * CLI: Errors occurred processing action add
 * Exception: Overlay "y2kbadbug" does not exist.

Following instructions from https://github.com/autokey/autokey

Thanks.

**Comment by y2kbadbug** [comment]
I stopped using Gentoo awhile ago, so my overlay is for historical purposes.  I am sure the ebuild could be simply modified and put into a local overlay.

**Comment by iandoug** [comment]
Thanks. Managed to get it working via PIP install method.
